### PR TITLE
Add warnings support and context for files options

### PR DESCRIPTION
**Pull request by vikshv**
It is necessary to implement the output of warnings. And support the context for the option "files"

### CODE REVIEW

**Comment by mgoodings** [comment]
I've added support for warnings with a separate commit and published v0.0.7.

I will look into context tomorrow. Personally I use a .stylelintignore files, are you sure this isn't an option?

**Comment by vikshv** [comment]
Thank you!
The use of a .stylelintignore is an option, but in stylelint-webpack-plugin automatically added a context and my config uses this option:
`{
    configFile: '.stylelintrc.json',
    context: 'src',
    files: [
        '**/*.css',
        '**/*.mcss'
    ]
}`
Without applying the context to the files, the plugin checks the dist directory. Of course you can add the dist directories to the .stylelintignore file

**Comment by mgoodings** [comment]
I added context path support to v0.0.8 based on your changes, can you please let me know if it's acceptable.

**Comment by vikshv** [comment]
Thank you! that's ok

**Pull request closed without merging**
